### ISSUE TITLE
Apply part segmentation on OUR OWN DATA

### ISSUE THREAD

**Issue by WadeYin9712** [facebookresearch/paco#1]
Hi! Thanks a lot for your amazing benchmark and code!

I wonder if you could provide some instructions on how to get part segments on our OWN DATA by the models you provided. It seems that right now the repo only offers the instruction to do inference on LVIS and Ego4D.

Thanks!

**Comment by anmolkalia** [comment]
This repo primarily support PACO dataset, but running on your own dataset should not be too hard if you've worked with detectron2 before.
You will need to write your own dataset.py file like paco.py which doesn't add any "annotations" to the dataset dict. So something like https://github.com/facebookresearch/paco/blob/main/paco/data/datasets/paco.py#L181 will need to be removed. Then the dataloader will only load images.

To save the masks, PacoEvaluator inherits from D2's LvisEvaluator and setting the output_dir https://github.com/facebookresearch/paco/blob/main/paco/evaluation/paco_evaluation.py#L37 will automatically save the masks to this file https://github.com/facebookresearch/detectron2/blob/main/detectron2/evaluation/lvis_evaluation.py#L116

**Comment by WadeYin9712** [comment]
Thank you so much!
