### ISSUE TITLE
test json

### ISSUE THREAD

**Issue by Heart-eartH** [facebookresearch/paco#13]
The paper reports results on test splits, but where can I get paco_lvis_v1_test.json to reproduce the results of the paper

**Comment by vpetrovi** [comment]
Thanks for your interest in our dataset! We were contemplating holding a challenge and held back the test sets for both PACO-LVIS and PACO-EGO4D. We decided to hold challenge on PACO-EGO4D only, we have updated paco_lvis_v1.zip file and included the test JSON, please try downloading the file again.
