### ISSUE TITLE
Score Calculation

### ISSUE THREAD

**Issue by krbuettner** [facebookresearch/paco#17]
Hi, I am interested in analyzing open-vocabulary detectors with the zero-shot instance detection task. I read in the paper (Appendix H) how Detic and MDETR were used, but I wanted to clarify if the query scores for the open-vocabulary detectors were computed in the same way as the PACO-trained models (Appendix G). If so, this repo supports such evaluation of open-vocabulary detectors, correct? 

Thank you for your time and consideration.

**Comment by vpetrovi** [comment]
Hi there, thanks for your interest in our paper and code. Yes, the code can be used for evaluation of any open-vocabulary instance detector.

So if you use 5k queries as prompts and dump scores for detected boxes for each image in a PACO dataset (e.g., paco_lvis_v1_test) to a .npy or .pth file, you can pass it to query_predictions_eval.py script (https://github.com/facebookresearch/paco/blob/12c1dad2e1eca69ed9a8128a23b31ef4302d8610/scripts/query_predictions_eval.py#L21) and it will do the eval on that dataset. The prediction dump format is specified in https://github.com/facebookresearch/paco/blob/12c1dad2e1eca69ed9a8128a23b31ef4302d8610/paco/evaluation/paco_query_evaluation.py#L497-L510.

To answer your question on score calculation, the open-vocabulary detectors directly produce scores for prompts for each of detected bounding boxes. PACO-trained models produce part and attribute scores for each of detected bounding boxes and these scores have to be converted to query scores as described in Appendix G. So the calculation is different but the final output format is the same: a set of boxes and query prediction scores. This allows the same evaluation script to be used for all methods (which is what we did).

Hope you can use it for your eval, let us know if you have any more questions.

**Comment by krbuettner** [comment]
Great, thanks for the excellent answer.

**Comment by vpetrovi** [comment]
Closing the issue, please feel free to reopen it if you have any more questions.
