### ISSUE TITLE
Typo in paper

### ISSUE THREAD

**Issue by hu-po** [facebookresearch/paco#3]
Great work! I think in section 3 you meant to say "belong to *small* and medium" size in this sentence (instead of *low*)

![image](https://user-images.githubusercontent.com/8493427/211850817-9df4860b-5287-4835-adbc-34b92acba3e3.png)

**Comment by vpetrovi** [comment]
Thanks for catching and reporting the typo! We have corrected it now, the fix will appear in the next revision of the paper.
